name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  NEXT_PUBLIC_API_URL: ${{ secrets.API_URL }}
  NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
  NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}

jobs:
  build-hosting:
    runs-on: ubuntu-latest
    container: 
      image: node:18.4.0-alpine

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm ci

    - name: Build
      run: npm run build

  lint-hosting:
    needs: [build-hosting]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Lint
      run: npm run lint:fix
    continue-on-error: true

  test-hosting:
    needs: [build-hosting]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Test
      run: npm run test

    - name: Npm Audit
      run: npm audit --audit-level=high

  deploy-functions:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Firebase Tools
      run: npm install -g firebase-tools

    - name: Setup Functions
      run: |
        cd functions
        npm ci

    - name: Deploy Functions
      run: |
        firebase use default
        firebase deploy --only functions --token ${{ secrets.FIREBASE_TOKEN }}

  deploy-hosting:
    needs: [test-hosting]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Firebase Tools
      run: npm install -g firebase-tools

    - name: Install Dependencies
      run: npm ci

    - name: Setup Functions
      run: |
        cd functions
        npm ci
        cd ..

    - name: Deploy Hosting
      run: |
        firebase use default
        firebase experiments:enable webframeworks
        firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}
